### ISSUE TITLE
Add GillesPy API

### ISSUE THREAD

**Issue by ahellander** [Molns/molns#34]
And provide similar abstractions for parallel ensembles and parameter sweeps as for pyurdme.

**Comment by ahellander** [comment]
I think this is complete?

**Comment by briandrawert** [comment]
I would like GillesPy installed by default.  I don't think that is the case at the moment.

**Comment by ahellander** [comment]
I know i have that in a branch, I will  find it and add it.

Skickat från min Samsung Mobil.

-------- Originalmeddelande --------
Från: Brian Drawert
Datum:09-11-2015 17:56 (GMT+01:00)
Till: Molns/molns
Kopia: Andreas Hellander
Rubrik: Re: [molns] Add GillesPy API (#34)

I would like GillesPy installed by default. I don't think that is the case at the moment.

**Comment by briandrawert** [comment]
This is in the stochss_integration branch (I think), so the problem is that it requires a install (and initial run) of StochSS to get both the stochastic and deterministic solvers working.

**Comment by ahellander** [comment]
I have a branch that only installs stochkit and gillespy. I dont want to run the whole stochss install unless the objective is to run  stochss.

Skickat från min Samsung Mobil.

-------- Originalmeddelande --------
Från: Brian Drawert
Datum:09-11-2015 19:24 (GMT+01:00)
Till: Molns/molns
Kopia: Andreas Hellander
Rubrik: Re: [molns] Add GillesPy API (#34)

This is in the stochss_integration branch (I think), so the problem is that it requires a install (and initial run) of StochSS to get both the stochastic and deterministic solvers working.

**Comment by briandrawert** [comment]
Excellent, can you send me a PR from that branch so I can test?

**Comment by briandrawert** [comment]
This was fixed in https://github.com/Molns/molns/pull/45
