### ISSUE TITLE
Latest FEniCS

### ISSUE THREAD

**Issue by bbbales2** [Molns/molns#39]
The latest FEniCS doesn't seem to be compatible with this.

I see these errors in my molns_install.log:

```
InstallSW.exec_command(source /usr/local/pyurdme/pyurdme_init && python -c 'import pyurdme')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/pyurdme/pyurdme/__init__.py", line 2, in <module>
    from .pyurdme import *
  File "/usr/local/pyurdme/pyurdme/pyurdme.py", line 38, in <module>
    raise Exception("PyURDME requires FeniCS/Dolfin.")
Exception: PyURDME requires FeniCS/Dolfin.

InstallSW.exec_command(source /usr/local/pyurdme/pyurdme_init && python -c 'import pyurdme') Exit Status=1
```

**Comment by ahellander** [comment]
They have removed the uBLAS backend:

> > > dolfin.parameters["linear_algebra_backend"]="uBLAS"  
> > > Traceback (most recent call last):  
> > >   File "<stdin>", line 1, in <module>  
> > >   File "/usr/lib/python2.7/dist-packages/dolfin/cpp/common.py", line 2353, in **setitem**  
> > >     par._assign(value)  
> > > RuntimeError:                                                                                               

**\* -------------------------------------------------------------------------  
**\* DOLFIN encountered an error. If you are not able to resolve this issue  
**\* using the information listed below, you can ask for help at                                             

---

**\*     fenics@fenicsproject.org                                                                            

---

**\* Remember to include the error message listed below and, if possible,  
**\* include a _minimal_ running example to reproduce the error.                                             

---

**\* -------------------------------------------------------------------------  
**\* Error:   Unable to assign parameter value.  
**\* Reason:  Illegal value for parameter "linear_algebra_backend". Allowed values are: [Eigen, PETSc, STL]. 
**\* Where:   This error was encountered inside Parameter.cpp.  
**\* Process: 0                                                                                              

---

**\* DOLFIN version: 1.6.0  
**\* Git changeset:  unknown  
**\* -------------------------------------------------------------------------

**Comment by ahellander** [comment]
https://bitbucket.org/fenics-project/dolfin/issues/528/remove-ublas-backend

**Comment by ahellander** [comment]
This is now fixed in pyurdme
