### ISSUE TITLE
controller list can show IP of active controllers

### ISSUE THREAD

**Issue by ahellander** [Molns/molns#46]
It would be nice if 
molns controller list showed the public IP of an active controller in a third column. 

Use case: You can't remember the IP of your controller and don't want to look it up ...

**Comment by briandrawert** [comment]
You can easily get the IP of the controller using the command: 'molns status CONTROLLER_NAME'.

**Comment by ahellander** [comment]
## I forgot that.  Ok, never mind. Although now I need to execute two commands.

Andreas Hellander
Associate Professor, Scientific Computing
Division of Scientific Computing
Department of Information Technology
Uppsala University

On Sep 18, 2015, at 9:03 AM, Brian Drawert <notifications@github.com<mailto:notifications@github.com>> wrote:

You can easily get the IP of the controller using the command: 'molns status CONTROLLER_NAME'.
