### ISSUE TITLE
Moving files to/from the head node

### ISSUE THREAD

**Issue by briandrawert** [Molns/molns#5]
Need a good way to move files to and from the MOLNs controller.  Possibilities:
1. commands to move individual files or folders (like scp) 
   - molns sync-up controller local-file-name
   - molns sync-down controller remote-file-name
2. SSHfs mount a folder (only on linux)
   - molns sshfs controller local-folder-name
3. Sync to/from a S3/Swift bucket (must be on same provider)
   - molns sync-from-cloud controller local-folder-name bucket-name
   - molns cloud-checkpoint controller local-folder-name bucket-name

**Comment by ahellander** [comment]
adding to this:
1. Extend the webpage with an upload form. 
2. Extend the drag and drop capabilities of the IPython home-page to accept any filetype. 
3. rsync a folder. 

1 above (scp). is simple, but maybe it should be
molns cp local-file-name controller.
or 
molns put local-file-name controller 

It is low-hanging fruit and satisfy the basic requirements.  

In addition, we should then extend molnsutil to push a file on the controller to all engines. I am thinking about mesh files for example. Alternatively, we need to assemble model objects on the controller node and push them over the wire (inefficient).

**Comment by briandrawert** [comment]
Referring to your numbers above:
for 4, I like "molns put" and "molns get".
for 1, there are web-app file managers.  We should look into that

**Comment by ahellander** [comment]
From actually having to do this today to push a meshfile to be accessible by the model class constructor, I feel that a quick and big improvement would be to enable

molns put [localfile] [clustername]

Which would 
scp -i xxx.pem localfile ubuntu@ip:/shared

Seems like the usecase for this is almost alwats to make a local datafile needed by some part of the computation globally accessible to workers.

**Comment by briandrawert** [comment]
molns put is implemented here: https://github.com/Molns/molns/pull/22

**Comment by briandrawert** [comment]
Closed in https://github.com/Molns/molns/pull/30
