### ISSUE TITLE
Export provider/controller setting

### ISSUE THREAD

**Issue by ahellander** [Molns/molns#59]
Would be nice with 
molns export <provider_name> 

so that we can easily export all setting as a file/db so that the same settings can be conveniently deployed by abother molns client.

**Comment by briandrawert** [comment]
This functionality exists, type:
`molns controller export NAME`
where "NAME" is the name of your controller.  This will create a file in  your current working directory named:
`Molns-Export-Controller-NAME.json`

**Comment by ahellander** [comment]
Aha, my bad. 

Can we also create a controller by specifying the json-file?

**Comment by briandrawert** [comment]
Yup!
`molns controller import Molns-Export-Controller-NAME.json`
will create a controller with the info from the JSON file.

**Comment by briandrawert** [comment]
This pattern is true of `provider`s and `worker`s as well.
